module CGTest where

import Ast

test_var = [VarDef TInt [Array (Identifier "a") (Number 10),Array (Identifier "b") (Number 20),Identifier "c"],VarDef TChar [Identifier "d",Identifier "e",Array (Identifier "f") (Number 30)]]

test_func = [FuncDef FVoid (Identifier "init") [] (ComdStmt [] [VarDef TInt [Identifier "i"]] (StmtList [ForStmt (Assign (Identifier "i") (Number 0)) (BinNode Ls (Identifier "i") (Number 10)) (Assign (Identifier "i") (BinNode Add (Identifier "i") (Number 1))) (Assign (Array (Identifier "a") (Identifier "i")) (Identifier "i")),ForStmt (Assign (Identifier "i") (Number 0)) (BinNode Ls (Identifier "i") (Number 20)) (Assign (Identifier "i") (BinNode Add (Identifier "i") (Number 1))) (StmtList [DoStmt (Assign (Array (Identifier "b") (Identifier "i")) (Array (Identifier "a") (BinNode Div (Identifier "i") (Number 2)))) (Number 0)]),Ret Empty])),FuncDef FInt (Identifier "calc") [(TInt,Identifier "zero1"),(TInt,Identifier "zero2")] (ComdStmt [] [VarDef TInt [Identifier "i"]] (StmtList [ForStmt (Assign (Identifier "i") (Number 0)) (BinNode Ls (Identifier "i") (Number 10)) Empty (StmtList [Assign (Identifier "zero1") (BinNode Add (Identifier "zero1") (BinNode Div (BinNode Mul (Array (Identifier "a") (Identifier "i")) (Array (Identifier "b") (Identifier "i"))) (BinNode Sub (BinNode Sub (BinNode Add (Identifier "i") (Number 1)) (Number 2)) (Number 3)))),Assign (Identifier "i") (BinNode Add (Identifier "i") (Number 1))]),ForStmt Empty (BinNode Ls (Identifier "i") (Number 20)) (Assign (Identifier "i") (BinNode Add (Identifier "i") (Number 1))) (StmtList [Assign (Identifier "zero2") (BinNode Sub (BinNode Add (BinNode Add (Identifier "zero2") (Identifier "zero1")) (Identifier "i")) (Number 10))]),Ret (BinNode Sub (BinNode Sub (BinNode Sub (BinNode Mul (Identifier "zero1") (Identifier "zero2")) (Identifier "zero2")) (Identifier "zero1")) (BinNode Div (Identifier "zero1") (Identifier "zero2")))])),FuncDef FVoid (Identifier "main") [] (ComdStmt [] [VarDef TInt [Identifier "z1",Identifier "z2"]] (StmtList [FuncCall (Identifier "init") [],Rd [Identifier "z1",Identifier "z2"],IfStmt (BinNode Gt (Identifier "z1") (Number 10)) (StmtList [Wt Empty (FuncCall (Identifier "calc") [Identifier "z1",Identifier "z2"])]) (StmtList [IfStmt (BinNode Gt (Identifier "z2") (Number 10)) (Wt Empty (FuncCall (Identifier "calc") [Identifier "z1",Number 10])) Empty])]))]


test_ast = Program [] [VarDef TInt [Array (Identifier "a") (Number 10),Array (Identifier "b") (Number 20),Identifier "c"],VarDef TChar [Identifier "d",Identifier "e",Array (Identifier "f") (Number 30)]] [FuncDef FVoid (Identifier "init") [] (ComdStmt [] [VarDef TInt [Identifier "i"]] (StmtList [ForStmt (Assign (Identifier "i") (Number 0)) (BinNode Ls (Identifier "i") (Number 10)) (Assign (Identifier "i") (BinNode Add (Identifier "i") (Number 1))) (Assign (Array (Identifier "a") (Identifier "i")) (Identifier "i")),ForStmt (Assign (Identifier "i") (Number 0)) (BinNode Ls (Identifier "i") (Number 20)) (Assign (Identifier "i") (BinNode Add (Identifier "i") (Number 1))) (StmtList [DoStmt (Assign (Array (Identifier "b") (Identifier "i")) (Array (Identifier "a") (BinNode Div (Identifier "i") (Number 2)))) (Number 0)]),Ret Empty])),FuncDef FInt (Identifier "calc") [(TInt,Identifier "zero1"),(TInt,Identifier "zero2")] (ComdStmt [] [VarDef TInt [Identifier "i"]] (StmtList [ForStmt (Assign (Identifier "i") (Number 0)) (BinNode Ls (Identifier "i") (Number 10)) Empty (StmtList [Assign (Identifier "zero1") (BinNode Add (Identifier "zero1") (BinNode Div (BinNode Mul (Array (Identifier "a") (Identifier "i")) (Array (Identifier "b") (Identifier "i"))) (BinNode Sub (BinNode Sub (BinNode Add (Identifier "i") (Number 1)) (Number 2)) (Number 3)))),Assign (Identifier "i") (BinNode Add (Identifier "i") (Number 1))]),ForStmt Empty (BinNode Ls (Identifier "i") (Number 20)) (Assign (Identifier "i") (BinNode Add (Identifier "i") (Number 1))) (StmtList [Assign (Identifier "zero2") (BinNode Sub (BinNode Add (BinNode Add (Identifier "zero2") (Identifier "zero1")) (Identifier "i")) (Number 10))]),Ret (BinNode Sub (BinNode Sub (BinNode Sub (BinNode Mul (Identifier "zero1") (Identifier "zero2")) (Identifier "zero2")) (Identifier "zero1")) (BinNode Div (Identifier "zero1") (Identifier "zero2")))])),FuncDef FVoid (Identifier "main") [] (ComdStmt [] [VarDef TInt [Identifier "z1",Identifier "z2"]] (StmtList [FuncCall (Identifier "init") [],Rd [Identifier "z1",Identifier "z2"],IfStmt (BinNode Gt (Identifier "z1") (Number 10)) (StmtList [Wt Empty (FuncCall (Identifier "calc") [Identifier "z1",Identifier "z2"])]) (StmtList [IfStmt (BinNode Gt (Identifier "z2") (Number 10)) (Wt Empty (FuncCall (Identifier "calc") [Identifier "z1",Number 10])) Empty])]))]

